sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  alioss:
    endpoint: ${ALIOSS_ENDPOINT}
    bucket-name: ${ALIOSS_BUCKET_NAME}
    access-key-secret: ${ALIOSS_ACCESS_KEY_SECRET}
    access-key-id: ${ALIOSS_ACCESS_KEY_ID}
  redis:
    host: localhost
    port: 6379
    password: ${REDIS_PASSWORD}
    database: 0
  wechat:
    appid: ${WECHAT_APPID}
    secret: ${WECHAT_SECRET}
  map:
    key: ${AMAP_KEY}
    adminAddress: ${SHOP_ADMIN_ADDRESS}
